version: 2

jobs:
  build-ut:
    docker:
      - image: golang:1.13
    working_directory: /go/src/github.com/DigitalChinaOpenSource/DCParser
    steps:
      - checkout
      - run:
          name: "Verify parser.go is up-to-date"
          command: |
            mv parser.go parser.go.committed
            make parser
            diff -u parser.go.committed parser.go
      - run:
          name: "Check code format"
          command: make fmt
      - run:
          name: "Build & Test"
          command: make test
      - run:
          name: "Upload coverage"
          command: bash <(curl -s https://codecov.io/bash)
workflows:
  version: 2
  build_and_test:
    jobs:
    - build-ut
